version: "3.8"

services:
  push_event:
    build: .
    container_name: push_event_worker
    image: lilhuy0405/4bytes-evm-token-indexer
    command: PushEvent -- --saveLog=0

  push_event_save_log:
    build: .
    container_name: push_event_worker_save_log
    image: lilhuy0405/4bytes-evm-token-indexer
    command: PushEvent -- --saveLog=1

  filter_event:
    build: .
    container_name: filter_event_worker
    image: lilhuy0405/4bytes-evm-token-indexer
    command: FilterEvent


  save_token_and_transfer:
    build: .
    container_name: save_token_and_transfer_worker
    image: lilhuy0405/4bytes-evm-token-indexer
    command: SaveTokenAndTransferEvent
  save_log:
    build: .
    container_name: save_log_worker
    image: lilhuy0405/4bytes-evm-token-indexer
    command: SaveLog

  save_transaction:
    build: .
    container_name: save_transaction_worker
    image: lilhuy0405/4bytes-evm-token-indexer
    command: SaveTransaction

  save_balance:
    build: .
    container_name: save_balance_worker
    image: lilhuy0405/4bytes-evm-token-indexer
    command: SaveBalance
