version: "3.8"

services:
  push_event:
    build: .
    container_name: push_event_worker
    image: lilhuy0405/4bytes-token-indexer
    volumes:
      - push_event_worker_log:/app/logs
    command: PushEvent

  filter_event:
    build: .
    container_name: filter_event_worker
    image: lilhuy0405/4bytes-token-indexer
    volumes:
      - filter_event_worker_log:/app/logs
    command: FilterEvent


  save_data:
    build: .
    container_name: save_data_worker
    image: lilhuy0405/4bytes-token-indexer
    volumes:
      - save_data_worker_log:/app/logs
    command: SaveData
  save_log:
    build: .
    container_name: save_log_worker
    image: lilhuy0405/4bytes-token-indexer
    volumes:
      - save_log_worker_log:/app/logs
    command: SaveLog

#Volume mounting for saving logs files
volumes:
  push_event_worker_log:
    name: push_event_worker_log
  filter_event_worker_log:
    name: filter_event_worker_log
  save_data_worker_log:
    name: save_data_worker_log
  save_log_worker_log:
    name: save_log_worker_log